# training options
context_size: 7
dev_batchsize: 128
encoder_units: 2048
feature_dim: 23
frame_shift: 80
frame_size: 200
use_last_samples: True
gpu: 1
gradclip: 5
hidden_size: 256
input_transform: logmel_meannorm
log_report_batches_num: 10
max_epochs: 100
model_type: DiaCorrect
num_frames: 500
num_speakers: 2
num_workers: 4
optimizer: adam
lr: 0.00001
output_path: exp/train_scratch_callhome
sampling_rate: 8000
seed: 3
subsampling: 10
train_batchsize: 32
transformer_encoder_dropout: 0.1
transformer_encoder_n_heads: 4
transformer_encoder_n_layers: 2
train_data_dir: 
train_sap_scp: sap/callhome_part1_2spk/sap.scp
valid_data_dir: 
valid_sap_scp: sap/callhome_part1_2spk/sap.scp
