# training options
attractor_loss_ratio: 1.0
attractor_encoder_dropout: 0.1
attractor_decoder_dropout: 0.1
context_size: 7
detach_attractor_loss: False
dev_batchsize: 128
encoder_units: 2048
feature_dim: 23
frame_shift: 80
frame_size: 200
use_last_samples: True
use_specaugment: False
gpu: 1
gradclip: 5
hidden_size: 256
input_transform: logmel_meannorm
log_report_batches_num: 10
max_epochs: 100
model_type: DiaCorrect
num_frames: 500
num_speakers: 2
num_workers: 4
optimizer: adam
lr: 0.00001
output_path: /mnt/matylda3/ihan/project/diarization/github/diacorrect/exp/train_scratch_callhome_lr_1e-5
sampling_rate: 8000
seed: 3
subsampling: 10
time_shuffle: True
train_batchsize: 32
transformer_encoder_dropout: 0.1
transformer_encoder_n_heads: 4
transformer_encoder_n_layers: 4
train_data_dir: /mnt/matylda4/landini/diarization/EEND/evaluation_sets/callhome_part1_2spk
train_sap_dir: sap/callhome_part1_2spk/sap.scp
valid_data_dir: /mnt/matylda4/landini/diarization/EEND/evaluation_sets/callhome_part1_2spk
valid_sap_dir: sap/callhome_part1_2spk/sap.scp
